language: minimal

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: shellcheck ./bin/*
    - stage: deploy
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
